In [ ]:
import numpy as np

In [1]:
import pandas as pd

In [2]:
pd.read_csv('../data/13_diecasting_shot - 복사본.csv')

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [13]:
df=pd.read_csv('../data/13_diecasting_shot - 복사본.csv')

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   샷       200 non-null    int64
 1   설비ID    200 non-null    str
 2   실린더압력   186 non-null    float64
 3   주조압력    186 non-null    float64
 4   사이클타임   186 non-null    float64
 5   비스킷두께   186 non-null    float64
 6   형체력     186 non-null    float64
 7   품질등급    200 non-null    str
dtypes: float64(5), int64(1), str(2)
memory usage: 15.4 KB

In [15]:
df.columns

Index(['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급'], dtype='str')

In [16]:
df[['형체력','실린더압력']]

       형체력  실린더압력
0    258.0  214.0
1    257.0  217.0
2    254.0  214.0
3    253.0  217.0
4    254.0  217.0
..     ...    ...
195  381.0  264.0
196  355.0  265.0
197  354.0  113.0
198  372.0  264.0
199  237.0  108.0

[200 rows x 2 columns]

In [7]:
two_colums=df[['형체력','실린더압력']]

In [18]:
two_colums.shape

(200, 2)

In [19]:
list(df.colums)

AttributeError: 'DataFrame' object has no attribute 'colums'

In [20]:
type(two_colums)

pandas.DataFrame

In [21]:
one_colums=df['형체력']

In [23]:
type(one_colums)

pandas.Series

In [24]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [25]:
df.index

RangeIndex(start=0, stop=200, step=1)

In [26]:
df.iloc[0]

샷               1
설비ID     DIE-A-01
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 0, dtype: object

In [27]:
df.loc[0]

샷               1
설비ID     DIE-A-01
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 0, dtype: object

In [28]:
df_copy=df.set_index('샷')

In [29]:
df_copy.index

RangeIndex(start=1, stop=201, step=1, name='샷')

In [30]:
df_copy

         설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
샷
1    DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
2    DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
3    DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
4    DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
5    DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..        ...    ...     ...     ...    ...    ...  ...
196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 7 columns]

In [32]:
df_copy.iloc[0]

설비ID     DIE-A-01
실린더압력       214.0
주조압력       1037.0
사이클타임        20.7
비스킷두께        10.0
형체력         258.0
품질등급           양품
Name: 1, dtype: object

In [34]:
df_copy.loc[0]

KeyError: 0

In [35]:
df

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[200 rows x 8 columns]

In [36]:
df.sort_values('형체력')

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
103  104  DIE-C-01    NaN     NaN     NaN    NaN    NaN   양품
104  105  DIE-A-01    NaN     NaN     NaN    NaN    NaN   양품
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량

[200 rows x 8 columns]

In [38]:
# 높은 값부터 정렬할때

In [37]:
df.sort_values('형체력', ascending=False)

       샷      설비ID  실린더압력   주조압력  사이클타임  비스킷두께    형체력 품질등급
171  172  DIE-A-01  265.0  595.0   36.1   17.0  384.0   양품
169  170  DIE-A-01  265.0  596.0   36.1   18.0  382.0   양품
166  167  DIE-B-01  264.0  595.0   35.9   18.0  382.0   양품
179  180  DIE-C-01  265.0  596.0   36.2   18.0  382.0   양품
168  169  DIE-A-01  265.0  596.0   36.1   18.0  382.0   양품
..   ...       ...    ...    ...    ...    ...    ...  ...
103  104  DIE-C-01    NaN    NaN    NaN    NaN    NaN   양품
104  105  DIE-A-01    NaN    NaN    NaN    NaN    NaN   양품
187  188  DIE-A-01    NaN    NaN    NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN    NaN    NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN    NaN    NaN    NaN    NaN   불량

[200 rows x 8 columns]

In [39]:
df_sorted_by_body=df.sort_values('형체력', ascending=False)

In [40]:
df_sorted_by_body.index[:4]

Index([171, 169, 166, 179], dtype='int64')

In [41]:
df_sorted_by_body.index[:4].to_list()

[171, 169, 166, 179]

In [43]:
df = pd.read_csv('..//data//13_diecasting_small.csv')

In [46]:
df.loc[0,'샷']

np.int64(1)

In [53]:
df.iloc[0]['샷']

np.int64(1)

In [49]:
df.sort_values('형체력', ascending=False)

     샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
22  23  DIE-B-01  265.0   595.0   33.9   19.0  359.0   주의
17  18  DIE-A-02  265.0   596.0   33.7   19.0  357.0   주의
27  28  DIE-C-01  265.0   595.0   33.8   19.0  355.0   주의
12  13  DIE-A-02  265.0   596.0   33.9   19.0  354.0   주의
19  20  DIE-A-01  216.0  1044.0   21.2   11.0  259.0   불량
0    1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
11  12  DIE-C-01  215.0  1038.0   20.9   11.0  258.0   양품
13  14  DIE-B-02  215.0  1039.0   20.9   11.0  258.0   양품
14  15  DIE-C-01  215.0  1041.0   21.3    4.0  258.0   불량
16  17  DIE-A-02  218.0  1054.0   21.0   11.0  258.0   양품
18  19  DIE-A-02  214.0  1038.0   20.8   11.0  257.0   양품
15  16  DIE-A-01  218.0  1053.0   20.8   12.0  257.0   양품
8    9  DIE-B-01  217.0  1052.0   20.6   11.0  257.0   양품
1    2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
21  22  DIE-B-01  218.0  1053.0   20.9   11.0  257.0   양품
20  21  DIE-C-01  214.0  1037.0   20.8   11.0  257.0   양품
26  27  DIE-C-01  217.0  1051.0   20.9   12.0  257.0   양품
23  24  DIE-A-01  214.0  1037.0   20.8   12.0  255.0   양품
25  26  DIE-A-01  218.0  1055.0   20.9   11.0  255.0   양품
24  25  DIE-A-02  219.0  1058.0   21.3    2.0  255.0   불량
28  29  DIE-B-02  218.0  1055.0   20.7   11.0  255.0   양품
7    8  DIE-C-01  235.0  1137.0   22.5    7.0  255.0   주의
6    7  DIE-B-02  217.0  1052.0   20.6   11.0  254.0   양품
3    4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
2    3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
5    6  DIE-A-02  217.0  1052.0   20.6   11.0  253.0   양품
29  30  DIE-A-02  218.0  1054.0   21.4    2.0  253.0   불량
10  11  DIE-A-01  215.0  1038.0   20.9   11.0  250.0   양품
9   10  DIE-C-01  214.0  1036.0   93.1   12.0  247.0   불량
4    5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [50]:
df_sorted_by_body=df.sort_values('형체력', ascending=False)

In [54]:
df_sorted_by_body.loc[0,'샷']

np.int64(1)

In [55]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [56]:
df.loc[0:4]

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량

In [57]:
df.loc[0:4],['형체력']

(   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
 0  1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
 1  2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
 2  3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
 3  4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
 4  5  DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량,
 ['형체력'])

In [61]:
df.loc[0:4, ['실린더압력','형체력']]

   실린더압력    형체력
0  214.0  258.0
1  217.0  257.0
2  215.0  253.0
3  214.0  254.0
4  108.0  222.0

In [62]:
df.loc[17:20,['설비ID','사이클타임','품질등급']]

        설비ID  사이클타임 품질등급
17  DIE-A-02   33.7   주의
18  DIE-A-02   20.8   양품
19  DIE-A-01   21.2   불량
20  DIE-C-01   20.8   양품

In [64]:
df.set_index('샷')

        설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
샷
1   DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
2   DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
3   DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
4   DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
5   DIE-C-01  108.0   522.0  652.3   14.0  222.0   불량
6   DIE-A-02  217.0  1052.0   20.6   11.0  253.0   양품
7   DIE-B-02  217.0  1052.0   20.6   11.0  254.0   양품
8   DIE-C-01  235.0  1137.0   22.5    7.0  255.0   주의
9   DIE-B-01  217.0  1052.0   20.6   11.0  257.0   양품
10  DIE-C-01  214.0  1036.0   93.1   12.0  247.0   불량
11  DIE-A-01  215.0  1038.0   20.9   11.0  250.0   양품
12  DIE-C-01  215.0  1038.0   20.9   11.0  258.0   양품
13  DIE-A-02  265.0   596.0   33.9   19.0  354.0   주의
14  DIE-B-02  215.0  1039.0   20.9   11.0  258.0   양품
15  DIE-C-01  215.0  1041.0   21.3    4.0  258.0   불량
16  DIE-A-01  218.0  1053.0   20.8   12.0  257.0   양품
17  DIE-A-02  218.0  1054.0   21.0   11.0  258.0   양품
18  DIE-A-02  265.0   596.0   33.7   19.0  357.0   주의
19  DIE-A-02  214.0  1038.0   20.8   11.0  257.0   양품
20  DIE-A-01  216.0  1044.0   21.2   11.0  259.0   불량
21  DIE-C-01  214.0  1037.0   20.8   11.0  257.0   양품
22  DIE-B-01  218.0  1053.0   20.9   11.0  257.0   양품
23  DIE-B-01  265.0   595.0   33.9   19.0  359.0   주의
24  DIE-A-01  214.0  1037.0   20.8   12.0  255.0   양품
25  DIE-A-02  219.0  1058.0   21.3    2.0  255.0   불량
26  DIE-A-01  218.0  1055.0   20.9   11.0  255.0   양품
27  DIE-C-01  217.0  1051.0   20.9   12.0  257.0   양품
28  DIE-C-01  265.0   595.0   33.8   19.0  355.0   주의
29  DIE-B-02  218.0  1055.0   20.7   11.0  255.0   양품
30  DIE-A-02  218.0  1054.0   21.4    2.0  253.0   불량

In [65]:
df_set=df.set_index('샷')

In [69]:
df_set.iloc[0:4]

       설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
샷
1  DIE-B-02  214.0  1037.0   20.7   10.0  258.0   양품
2  DIE-C-01  217.0  1052.0   20.7   11.0  257.0   양품
3  DIE-A-02  215.0  1040.0   20.7   21.0  253.0   주의
4  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품

In [76]:
df_set.iloc[0:4]['실린더압력']

샷
1    214.0
2    217.0
3    215.0
4    214.0
Name: 실린더압력, dtype: float64

In [80]:
df_set.loc[[3,7,15],['설비ID','비스킷두께','품질등급']]

        설비ID  비스킷두께 품질등급
샷
3   DIE-A-02   21.0   주의
7   DIE-B-02   11.0   양품
15  DIE-C-01    4.0   불량

In [81]:
df_set.loc[7]['비스킷두께']

np.float64(11.0)

In [83]:
df_set.loc[[7,15], ['설비ID','품질등급']]

        설비ID 품질등급
샷
7   DIE-B-02   양품
15  DIE-C-01   불량

In [84]:
df=pd.read_csv('../data/13_diecasting_shot - 복사본.csv')

In [85]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [88]:
df.columns

Index(['샷', '설비ID', '실린더압력', '주조압력', '사이클타임', '비스킷두께', '형체력', '품질등급'], dtype='str')

In [89]:
df.loc[0:9, ['설비ID','비스킷두께','품질등급']]

       설비ID  비스킷두께 품질등급
0  DIE-A-01   10.0   양품
1  DIE-B-01   11.0   양품
2  DIE-B-01   11.0   양품
3  DIE-B-02   11.0   양품
4  DIE-A-01   11.0   양품
5  DIE-A-01   11.0   양품
6  DIE-A-01   11.0   양품
7  DIE-A-01   11.0   양품
8  DIE-B-02   11.0   양품
9  DIE-A-01   12.0   양품

In [92]:
df_front10=df.loc[0:9, ['설비ID','비스킷두께','품질등급']]

In [93]:
df_front10

       설비ID  비스킷두께 품질등급
0  DIE-A-01   10.0   양품
1  DIE-B-01   11.0   양품
2  DIE-B-01   11.0   양품
3  DIE-B-02   11.0   양품
4  DIE-A-01   11.0   양품
5  DIE-A-01   11.0   양품
6  DIE-A-01   11.0   양품
7  DIE-A-01   11.0   양품
8  DIE-B-02   11.0   양품
9  DIE-A-01   12.0   양품

In [95]:
df.iloc[-5:]

       샷      설비ID  실린더압력   주조압력   사이클타임  비스킷두께    형체력 품질등급
195  196  DIE-A-01  264.0  594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0  595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0  255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0  595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0  525.0  6170.0   15.0  237.0   불량