In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../data/13_diecasting_shot.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   샷       200 non-null    int64
 1   설비ID    200 non-null    str
 2   실린더압력   186 non-null    float64
 3   주조압력    186 non-null    float64
 4   사이클타임   186 non-null    float64
 5   비스킷두께   186 non-null    float64
 6   형체력     186 non-null    float64
 7   품질등급    200 non-null    str
dtypes: float64(5), int64(1), str(2)
memory usage: 15.4 KB

In [4]:
df.head()

   샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0  1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1  2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2  3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3  4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4  5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품

In [5]:
df['비스킷두께']>=16

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Name: 비스킷두께, Length: 200, dtype: bool

In [6]:
con=df['비스킷두께']>=16

In [7]:
con.sum()

np.int64(74)

In [10]:
con2=df['비스킷두께']<16

In [16]:
con2

0       True
1       True
2       True
3       True
4       True
       ...
195    False
196    False
197    False
198    False
199     True
Name: 비스킷두께, Length: 200, dtype: bool

In [11]:
con2.sum()

np.int64(112)

In [14]:
(74+112)

186

In [15]:
df['비스킷두께'].isna().sum()

np.int64(14)

In [17]:
df['비스킷두께']>=16

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Name: 비스킷두께, Length: 200, dtype: bool

In [18]:
df['사이클타임']>=25

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199     True
Name: 사이클타임, Length: 200, dtype: bool

In [19]:
(df['비스킷두께']>=16) & (df['사이클타임']>=25)

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Length: 200, dtype: bool

In [20]:
both=(df['비스킷두께']>=16) & (df['사이클타임']>=25)

In [21]:
df[both]

       샷      설비ID  실린더압력   주조압력  사이클타임  비스킷두께    형체력 품질등급
108  109  DIE-A-01  264.0  594.0   36.4   18.0  363.0   양품
109  110  DIE-A-02  265.0  596.0   36.6   17.0  352.0   양품
110  111  DIE-A-02  264.0  595.0   37.0   18.0  361.0   양품
111  112  DIE-B-02  265.0  595.0   36.9   17.0  355.0   양품
112  113  DIE-A-01  264.0  594.0   33.9   16.0  363.0   양품
..   ...       ...    ...    ...    ...    ...    ...  ...
194  195  DIE-A-02  260.0  585.0   33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0  594.0   76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0  595.0   36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0  255.0   36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0  595.0   36.1   19.0  372.0   불량

[72 rows x 8 columns]

In [22]:
(df['비스킷두께']>=16) | (df['사이클타임']>=25)

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199     True
Length: 200, dtype: bool

In [23]:
either =(df['비스킷두께']>=16) | (df['사이클타임']>=25)

In [24]:
df[either]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0    20.7   21.0  253.0   주의
67    68  DIE-B-02  215.0  1040.0    21.1   17.0  257.0   양품
108  109  DIE-A-01  264.0   594.0    36.4   18.0  363.0   양품
109  110  DIE-A-02  265.0   596.0    36.6   17.0  352.0   양품
110  111  DIE-A-02  264.0   595.0    37.0   18.0  361.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[86 rows x 8 columns]

In [25]:
# ~ tilder

In [36]:
~5+1

-5

In [37]:
5+(~5+1)

0

In [38]:
df['품질등급']

0      양품
1      양품
2      양품
3      양품
4      양품
       ..
195    불량
196    불량
197    불량
198    불량
199    불량
Name: 품질등급, Length: 200, dtype: str

In [39]:
df['품질등급'] == '불량'

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199     True
Name: 품질등급, Length: 200, dtype: bool

In [40]:
df[df['품질등급'] == '불량']

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

In [42]:
len(df[df['품질등급'] == '불량'])

20

In [41]:
~(df['품질등급'] == '불량')

0       True
1       True
2       True
3       True
4       True
       ...
195    False
196    False
197    False
198    False
199    False
Name: 품질등급, Length: 200, dtype: bool

In [43]:
df[~(df['품질등급'] == '불량')]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0   20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0   20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0   20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0   20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0   20.6   11.0  254.0   양품
..   ...       ...    ...     ...    ...    ...    ...  ...
175  176  DIE-B-02  265.0   596.0   36.0   17.0  359.0   양품
176  177  DIE-A-01  264.0   595.0   36.0   17.0  361.0   양품
177  178  DIE-B-02  264.0   595.0   36.0   17.0  355.0   양품
178  179  DIE-B-01  265.0   595.0   36.1   16.0  372.0   양품
179  180  DIE-C-01  265.0   596.0   36.2   18.0  382.0   양품

[180 rows x 8 columns]

In [44]:
len(df[~(df['품질등급'] == '불량')])

180

In [47]:
len((df['비스킷두께']>=16) & (df['사이클타임']>=25))

200

In [48]:
len(both)

200

In [49]:
df['품질등급']

0      양품
1      양품
2      양품
3      양품
4      양품
       ..
195    불량
196    불량
197    불량
198    불량
199    불량
Name: 품질등급, Length: 200, dtype: str

In [50]:
df['품질등급'].isin(['주의'])

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: 품질등급, Length: 200, dtype: bool

In [51]:
df['품질등급'].isin(['주의']).count()

np.int64(200)

In [52]:
df['품질등급'].isin(['주의',['불량']])

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: 품질등급, Length: 200, dtype: bool

In [54]:
df[df['품질등급'].isin(['주의','불량'])]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0    20.7   21.0  253.0   주의
89    90  DIE-A-02  235.0  1137.0    22.5    7.0  255.0   주의
120  121  DIE-A-01  265.0   596.0    33.9   19.0  354.0   주의
122  123  DIE-C-01  265.0   596.0    33.7   19.0  357.0   주의
123  124  DIE-B-02  265.0   595.0    33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0    33.8   19.0  355.0   주의
132  133  DIE-A-01  265.0   596.0    35.0   19.0  373.0   주의
135  136  DIE-A-02  265.0   595.0    36.0   19.0  377.0   주의
146  147  DIE-A-02  263.0   592.0   125.9   19.0  372.0   주의
148  149  DIE-B-02  265.0   596.0    36.0   19.0  377.0   주의
149  150  DIE-A-01  265.0   596.0    36.1   19.0  350.0   주의
151  152  DIE-A-01  265.0   595.0    35.9   19.0  381.0   주의
152  153  DIE-A-02  265.0   595.0    36.0   19.0  352.0   주의
154  155  DIE-A-01  265.0   595.0    35.8   19.0  363.0   주의
155  156  DIE-A-01  265.0   596.0    35.7   19.0  364.0   주의
163  164  DIE-B-02  265.0   595.0    35.8   19.0  379.0   주의
167  168  DIE-A-01  265.0   596.0    36.0   19.0  379.0   주의
170  171  DIE-B-02  265.0   596.0    36.1   20.0  370.0   주의
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

In [55]:
len(df[df['품질등급'].isin(['주의','불량'])])

38

In [59]:
df['비스킷두께'].between(10,16)

0       True
1       True
2       True
3       True
4       True
       ...
195    False
196    False
197    False
198    False
199     True
Name: 비스킷두께, Length: 200, dtype: bool

In [58]:
len(df[df['비스킷두께'].between(10,16)])

117

In [62]:
df['비스킷두께'].isna().sum()

np.int64(14)

In [64]:
len(df[~df['비스킷두께'].between(10,16)])

83

In [65]:
df['설비ID']

0      DIE-A-01
1      DIE-B-01
2      DIE-B-01
3      DIE-B-02
4      DIE-A-01
         ...
195    DIE-A-01
196    DIE-A-01
197    DIE-A-01
198    DIE-B-02
199    DIE-A-01
Name: 설비ID, Length: 200, dtype: str

In [67]:
df['설비ID'].str.contains('A')

0       True
1      False
2      False
3      False
4       True
       ...
195     True
196     True
197     True
198    False
199     True
Name: 설비ID, Length: 200, dtype: bool

In [68]:
df[df['설비ID'].str.contains('A')]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
5      6  DIE-A-01  217.0  1052.0    20.6   11.0  257.0   양품
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
7      8  DIE-A-01  215.0  1038.0    20.9   11.0  258.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[111 rows x 8 columns]

In [69]:
'DIE-A-01'.split('-')[1]

'A'

In [ ]:
df['설비ID'].str.split('-')

0      [DIE, A, 01]
1      [DIE, B, 01]
2      [DIE, B, 01]
3      [DIE, B, 02]
4      [DIE, A, 01]
           ...
195    [DIE, A, 01]
196    [DIE, A, 01]
197    [DIE, A, 01]
198    [DIE, B, 02]
199    [DIE, A, 01]
Name: 설비ID, Length: 200, dtype: object

In [73]:
df['설비ID'].str.replace('DIE-','')

0      A-01
1      B-01
2      B-01
3      B-02
4      A-01
       ...
195    A-01
196    A-01
197    A-01
198    B-02
199    A-01
Name: 설비ID, Length: 200, dtype: str

In [74]:
df['품질등급'].isin(['주의,불량'])

0      False
1      False
2      False
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199    False
Name: 품질등급, Length: 200, dtype: bool

In [76]:
df_con=df[df['품질등급'].isin(['주의,불량'])]

In [77]:
len(df_con)

0

In [78]:
df['비스킷두께'].between(10,16)

0       True
1       True
2       True
3       True
4       True
       ...
195    False
196    False
197    False
198    False
199     True
Name: 비스킷두께, Length: 200, dtype: bool

In [80]:
th=df[df['비스킷두께'].between(10,16)]

In [82]:
th

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[117 rows x 8 columns]

In [81]:
len(th)

117

In [83]:
df['설비ID'].str.split('-')

0      [DIE, A, 01]
1      [DIE, B, 01]
2      [DIE, B, 01]
3      [DIE, B, 02]
4      [DIE, A, 01]
           ...
195    [DIE, A, 01]
196    [DIE, A, 01]
197    [DIE, A, 01]
198    [DIE, B, 02]
199    [DIE, A, 01]
Name: 설비ID, Length: 200, dtype: object

In [84]:
df['설비ID'].str.replace('DIE-','')

0      A-01
1      B-01
2      B-01
3      B-02
4      A-01
       ...
195    A-01
196    A-01
197    A-01
198    B-02
199    A-01
Name: 설비ID, Length: 200, dtype: str

In [86]:
df_A=df['설비ID'].str.replace('DIE-','')

In [88]:
df_A

0      A-01
1      B-01
2      B-01
3      B-02
4      A-01
       ...
195    A-01
196    A-01
197    A-01
198    B-02
199    A-01
Name: 설비ID, Length: 200, dtype: str

In [87]:
len(df_A)

200

In [91]:
df[df['설비ID']==('DIE-A-01')]

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
5      6  DIE-A-01  217.0  1052.0    20.6   11.0  257.0   양품
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
7      8  DIE-A-01  215.0  1038.0    20.9   11.0  258.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[63 rows x 8 columns]

In [92]:
A=df[df['설비ID']==('DIE-A-01')]

In [93]:
len(A)

63

In [94]:
A

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품
5      6  DIE-A-01  217.0  1052.0    20.6   11.0  257.0   양품
6      7  DIE-A-01  215.0  1038.0    20.9   11.0  250.0   양품
7      8  DIE-A-01  215.0  1038.0    20.9   11.0  258.0   양품
..   ...       ...    ...     ...     ...    ...    ...  ...
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

[63 rows x 8 columns]

In [95]:
df.sort_values(['품질등급', '사이클타임'])

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
183  184  DIE-B-01  216.0  1044.0   21.2   11.0  259.0   불량
182  183  DIE-A-02  215.0  1041.0   21.3    4.0  258.0   불량
184  185  DIE-B-01  219.0  1058.0   21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0   21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0   22.9   14.0  247.0   불량
..   ...       ...    ...     ...    ...    ...    ...  ...
152  153  DIE-A-02  265.0   595.0   36.0   19.0  352.0   주의
167  168  DIE-A-01  265.0   596.0   36.0   19.0  379.0   주의
149  150  DIE-A-01  265.0   596.0   36.1   19.0  350.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
146  147  DIE-A-02  263.0   592.0  125.9   19.0  372.0   주의

[200 rows x 8 columns]

In [96]:
df.sort_values(['품질등급', '사이클타임'],ascending=[True,False])

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
..   ...       ...    ...     ...     ...    ...    ...  ...
123  124  DIE-B-02  265.0   595.0    33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0    33.8   19.0  355.0   주의
122  123  DIE-C-01  265.0   596.0    33.7   19.0  357.0   주의
89    90  DIE-A-02  235.0  1137.0    22.5    7.0  255.0   주의
42    43  DIE-A-01  215.0  1040.0    20.7   21.0  253.0   주의

[200 rows x 8 columns]

In [97]:
df.nlargest(5,'비스킷두께')

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량

In [101]:
df.sort_values('비스킷두께', ascending=False)

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량
..   ...       ...    ...     ...    ...    ...    ...  ...
103  104  DIE-C-01    NaN     NaN    NaN    NaN    NaN   양품
104  105  DIE-A-01    NaN     NaN    NaN    NaN    NaN   양품
187  188  DIE-A-01    NaN     NaN    NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN    NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN    NaN    NaN    NaN   불량

[200 rows x 8 columns]

In [102]:
df_b=df.sort_values('비스킷두께', ascending=False)

In [103]:
df_b.head()

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량

In [107]:
df.sort_values(['품질등급','사이클타임'], ascending=[True,False]).head()

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량

In [109]:
df.nlargest(5,'비스킷두께')

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량

In [111]:
df[df['품질등급'] == '불량'].copy()

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량

In [112]:
불량=df[df['품질등급'] == '불량'].copy()

In [113]:
불량['위험등급'] = '높음'

In [114]:
불량

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급 위험등급
180  181  DIE-B-01  108.0   522.0   652.3   14.0  222.0   불량   높음
181  182  DIE-C-01  214.0  1036.0    93.1   12.0  247.0   불량   높음
182  183  DIE-A-02  215.0  1041.0    21.3    4.0  258.0   불량   높음
183  184  DIE-B-01  216.0  1044.0    21.2   11.0  259.0   불량   높음
184  185  DIE-B-01  219.0  1058.0    21.3    2.0  255.0   불량   높음
185  186  DIE-B-02  218.0  1054.0    21.4    2.0  253.0   불량   높음
186  187  DIE-C-01  108.0   524.0    22.9   14.0  247.0   불량   높음
187  188  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량   높음
188  189  DIE-A-01    NaN     NaN     NaN    NaN    NaN   불량   높음
189  190  DIE-B-01    NaN     NaN     NaN    NaN    NaN   불량   높음
190  191  DIE-B-02  238.0  1152.0    91.2   13.0  254.0   불량   높음
191  192  DIE-B-01  113.0   255.0    36.9   26.0  366.0   불량   높음
192  193  DIE-A-02  264.0   594.0    36.9   19.0  355.0   불량   높음
193  194  DIE-C-01  113.0   255.0    34.4   19.0  370.0   불량   높음
194  195  DIE-A-02  260.0   585.0    33.9   19.0  348.0   불량   높음
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량   높음
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량   높음
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량   높음
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량   높음
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량   높음

In [115]:
불량.shape

(20, 9)

In [116]:
판정=df.copy()

In [120]:
판정['설비ID'].str.split('-')

0      [DIE, A, 01]
1      [DIE, B, 01]
2      [DIE, B, 01]
3      [DIE, B, 02]
4      [DIE, A, 01]
           ...
195    [DIE, A, 01]
196    [DIE, A, 01]
197    [DIE, A, 01]
198    [DIE, B, 02]
199    [DIE, A, 01]
Name: 설비ID, Length: 200, dtype: object

In [ ]:
판정['설비ID'].str.split('-')

In [122]:
판정['설비ID'].str.split('-').str[1]

0      A
1      B
2      B
3      B
4      A
      ..
195    A
196    A
197    A
198    B
199    A
Name: 설비ID, Length: 200, dtype: object

In [124]:
판정['라인']=판정['설비ID'].str.split('-').str[1]

In [125]:
판정

       샷      설비ID  실린더압력    주조압력   사이클타임  비스킷두께    형체력 품질등급 라인
0      1  DIE-A-01  214.0  1037.0    20.7   10.0  258.0   양품  A
1      2  DIE-B-01  217.0  1052.0    20.7   11.0  257.0   양품  B
2      3  DIE-B-01  214.0  1037.0    20.8   11.0  254.0   양품  B
3      4  DIE-B-02  217.0  1052.0    20.6   11.0  253.0   양품  B
4      5  DIE-A-01  217.0  1052.0    20.6   11.0  254.0   양품  A
..   ...       ...    ...     ...     ...    ...    ...  ... ..
195  196  DIE-A-01  264.0   594.0    76.3   19.0  381.0   불량  A
196  197  DIE-A-01  265.0   595.0    36.2   20.0  355.0   불량  A
197  198  DIE-A-01  113.0   255.0    36.6   27.0  354.0   불량  A
198  199  DIE-B-02  264.0   595.0    36.1   19.0  372.0   불량  B
199  200  DIE-A-01  108.0   525.0  6170.0   15.0  237.0   불량  A

[200 rows x 9 columns]

In [126]:
판정['비스킷두께'] >=16

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199    False
Name: 비스킷두께, Length: 200, dtype: bool

In [127]:
판정. loc[판정['비스킷두께'] >=16,]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급 라인
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의  A
67    68  DIE-B-02  215.0  1040.0   21.1   17.0  257.0   양품  B
108  109  DIE-A-01  264.0   594.0   36.4   18.0  363.0   양품  A
109  110  DIE-A-02  265.0   596.0   36.6   17.0  352.0   양품  A
110  111  DIE-A-02  264.0   595.0   37.0   18.0  361.0   양품  A
..   ...       ...    ...     ...    ...    ...    ...  ... ..
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량  A
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량  A
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량  A
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량  A
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량  B

[74 rows x 9 columns]

In [132]:
df['품질등급']!='양품'

0      False
1      False
2      False
3      False
4      False
       ...
195     True
196     True
197     True
198     True
199     True
Name: 품질등급, Length: 200, dtype: bool

In [134]:
df[(df['품질등급']!='양품') & (df['비스킷두께'] >= 16)]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
120  121  DIE-A-01  265.0   596.0   33.9   19.0  354.0   주의
122  123  DIE-C-01  265.0   596.0   33.7   19.0  357.0   주의
123  124  DIE-B-02  265.0   595.0   33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0   33.8   19.0  355.0   주의
132  133  DIE-A-01  265.0   596.0   35.0   19.0  373.0   주의
135  136  DIE-A-02  265.0   595.0   36.0   19.0  377.0   주의
146  147  DIE-A-02  263.0   592.0  125.9   19.0  372.0   주의
148  149  DIE-B-02  265.0   596.0   36.0   19.0  377.0   주의
149  150  DIE-A-01  265.0   596.0   36.1   19.0  350.0   주의
151  152  DIE-A-01  265.0   595.0   35.9   19.0  381.0   주의
152  153  DIE-A-02  265.0   595.0   36.0   19.0  352.0   주의
154  155  DIE-A-01  265.0   595.0   35.8   19.0  363.0   주의
155  156  DIE-A-01  265.0   596.0   35.7   19.0  364.0   주의
163  164  DIE-B-02  265.0   595.0   35.8   19.0  379.0   주의
167  168  DIE-A-01  265.0   596.0   36.0   19.0  379.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0   36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0   34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량

In [137]:
df[(df['품질등급']!='양품') & (df['비스킷두께'] >= 16)]

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
120  121  DIE-A-01  265.0   596.0   33.9   19.0  354.0   주의
122  123  DIE-C-01  265.0   596.0   33.7   19.0  357.0   주의
123  124  DIE-B-02  265.0   595.0   33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0   33.8   19.0  355.0   주의
132  133  DIE-A-01  265.0   596.0   35.0   19.0  373.0   주의
135  136  DIE-A-02  265.0   595.0   36.0   19.0  377.0   주의
146  147  DIE-A-02  263.0   592.0  125.9   19.0  372.0   주의
148  149  DIE-B-02  265.0   596.0   36.0   19.0  377.0   주의
149  150  DIE-A-01  265.0   596.0   36.1   19.0  350.0   주의
151  152  DIE-A-01  265.0   595.0   35.9   19.0  381.0   주의
152  153  DIE-A-02  265.0   595.0   36.0   19.0  352.0   주의
154  155  DIE-A-01  265.0   595.0   35.8   19.0  363.0   주의
155  156  DIE-A-01  265.0   596.0   35.7   19.0  364.0   주의
163  164  DIE-B-02  265.0   595.0   35.8   19.0  379.0   주의
167  168  DIE-A-01  265.0   596.0   36.0   19.0  379.0   주의
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
192  193  DIE-A-02  264.0   594.0   36.9   19.0  355.0   불량
193  194  DIE-C-01  113.0   255.0   34.4   19.0  370.0   불량
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량

In [141]:
w=df[(df['품질등급']!='양품') & (df['비스킷두께'] >= 16)]

In [142]:
w.sort_values('비스킷두께', ascending=(False))

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의
120  121  DIE-A-01  265.0   596.0   33.9   19.0  354.0   주의
122  123  DIE-C-01  265.0   596.0   33.7   19.0  357.0   주의
123  124  DIE-B-02  265.0   595.0   33.9   19.0  359.0   주의
124  125  DIE-A-01  265.0   595.0   33.8   19.0  355.0   주의
148  149  DIE-B-02  265.0   596.0   36.0   19.0  377.0   주의
146  147  DIE-A-02  263.0   592.0  125.9   19.0  372.0   주의
135  136  DIE-A-02  265.0   595.0   36.0   19.0  377.0   주의
132  133  DIE-A-01  265.0   596.0   35.0   19.0  373.0   주의
154  155  DIE-A-01  265.0   595.0   35.8   19.0  363.0   주의
149  150  DIE-A-01  265.0   596.0   36.1   19.0  350.0   주의
152  153  DIE-A-02  265.0   595.0   36.0   19.0  352.0   주의
151  152  DIE-A-01  265.0   595.0   35.9   19.0  381.0   주의
167  168  DIE-A-01  265.0   596.0   36.0   19.0  379.0   주의
163  164  DIE-B-02  265.0   595.0   35.8   19.0  379.0   주의
155  156  DIE-A-01  265.0   596.0   35.7   19.0  364.0   주의
192  193  DIE-A-02  264.0   594.0   36.9   19.0  355.0   불량
194  195  DIE-A-02  260.0   585.0   33.9   19.0  348.0   불량
193  194  DIE-C-01  113.0   255.0   34.4   19.0  370.0   불량
195  196  DIE-A-01  264.0   594.0   76.3   19.0  381.0   불량
198  199  DIE-B-02  264.0   595.0   36.1   19.0  372.0   불량

In [143]:
w.sort_values('비스킷두께', ascending=(False)).head()

       샷      설비ID  실린더압력    주조압력  사이클타임  비스킷두께    형체력 품질등급
197  198  DIE-A-01  113.0   255.0   36.6   27.0  354.0   불량
191  192  DIE-B-01  113.0   255.0   36.9   26.0  366.0   불량
42    43  DIE-A-01  215.0  1040.0   20.7   21.0  253.0   주의
196  197  DIE-A-01  265.0   595.0   36.2   20.0  355.0   불량
170  171  DIE-B-02  265.0   596.0   36.1   20.0  370.0   주의

In [144]:
li=w.sort_values('비스킷두께', ascending=(False))

In [148]:
li[['설비ID','비스킷두께','품질등급']]

         설비ID  비스킷두께 품질등급
197  DIE-A-01   27.0   불량
191  DIE-B-01   26.0   불량
42   DIE-A-01   21.0   주의
196  DIE-A-01   20.0   불량
170  DIE-B-02   20.0   주의
120  DIE-A-01   19.0   주의
122  DIE-C-01   19.0   주의
123  DIE-B-02   19.0   주의
124  DIE-A-01   19.0   주의
148  DIE-B-02   19.0   주의
146  DIE-A-02   19.0   주의
135  DIE-A-02   19.0   주의
132  DIE-A-01   19.0   주의
154  DIE-A-01   19.0   주의
149  DIE-A-01   19.0   주의
152  DIE-A-02   19.0   주의
151  DIE-A-01   19.0   주의
167  DIE-A-01   19.0   주의
163  DIE-B-02   19.0   주의
155  DIE-A-01   19.0   주의
192  DIE-A-02   19.0   불량
194  DIE-A-02   19.0   불량
193  DIE-C-01   19.0   불량
195  DIE-A-01   19.0   불량
198  DIE-B-02   19.0   불량

In [149]:
li2=li[['설비ID','비스킷두께','품질등급']]

In [150]:
li2.head()

         설비ID  비스킷두께 품질등급
197  DIE-A-01   27.0   불량
191  DIE-B-01   26.0   불량
42   DIE-A-01   21.0   주의
196  DIE-A-01   20.0   불량
170  DIE-B-02   20.0   주의